--TB_USUARIOS
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Luciene Alves','luciene','123456');
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Assis Lima','assis','123456');
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Carlos Roberto','roberto','123456');
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Super Boss','Boss','123456');

--TB_ROLES
-- INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Admin');
-- INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Supervisor');
-- INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Auxiliar');

--TB_ROLES POR TB_USUARIOS
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (1,1);
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (2,2);
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,3);
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,4);

--Remove as Operadoras
DELETE FROM TB_OPERADORAS WHERE CO_OPERADORA>1;

--TB_OPERADORAS
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (14,'Oi','C');
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (15,'Vivo','C');
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (41,'Tim','C');
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (28,'Embratel','F');


--Remove os Contatos
DELETE FROM TB_CONTATOS WHERE NU_CONTATO>=1;

--TB_CONTATOS
INSERT INTO TB_CONTATOS(NU_CONTATO,NO_NOME_CONTATO,NM_TELEFONE_CONTATO,CO_OPERADORA,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'Carlos Roberto Medeiros','(61)99999-9999',14,TO_DATE('2021-06-01','yyyy-MM-dd'));
INSERT INTO TB_CONTATOS(NU_CONTATO,NO_NOME_CONTATO,NM_TELEFONE_CONTATO,CO_OPERADORA,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'Luciene Alves Medeiros','(61)8888-8888',15,TO_DATE('2021-05-02','yyyy-MM-dd'));
INSERT INTO TB_CONTATOS(NU_CONTATO,NO_NOME_CONTATO,NM_TELEFONE_CONTATO,CO_OPERADORA,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'Antonio Nunes Silva','(61)7777-7777',15,TO_DATE('2021-05-03','yyyy-MM-dd'));
INSERT INTO TB_CONTATOS(NU_CONTATO,NO_NOME_CONTATO,NM_TELEFONE_CONTATO,CO_OPERADORA,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'Lucia Maria','(61)6666-6666',41,TO_DATE('2021-05-04','yyyy-MM-dd'));
INSERT INTO TB_CONTATOS(NU_CONTATO,NO_NOME_CONTATO,NM_TELEFONE_CONTATO,CO_OPERADORA,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'Assis Lima','(61)5555-5555',28,TO_DATE('2021-05-20','yyyy-MM-dd'));




