--TB_USUARIOS
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Luciene Alves','luciene','123456');
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Assis Lima','assis','123456');
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Carlos Roberto','roberto','123456');
-- INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Super Boss','Boss','123456');

--TB_ROLES
-- INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Admin');
-- INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Supervisor');
-- INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Auxiliar');

--TB_ROLES POR TB_USUARIOS
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (1,1);
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (2,2);
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,3);
-- INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,4);

--TB_CONTATOS
INSERT INTO TB_CONTATOS(NU_CONTATO,CO_CPF_CONTATO,NO_NOME_CONTATO,CO_TELEFONE_CONTATO,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'2166666666','Carlos Roberto Medeiros','61999999999','2021-06-01');
INSERT INTO TB_CONTATOS(NU_CONTATO,CO_CPF_CONTATO,NO_NOME_CONTATO,CO_TELEFONE_CONTATO,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'6122225555','Luciene Alves Medeiros','6188888888','2021-05-02');
INSERT INTO TB_CONTATOS(NU_CONTATO,CO_CPF_CONTATO,NO_NOME_CONTATO,CO_TELEFONE_CONTATO,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'8122225555','Antonio Nunes Silva','6177777777','2021-05-03'));
INSERT INTO TB_CONTATOS(NU_CONTATO,CO_CPF_CONTATO,NO_NOME_CONTATO,CO_TELEFONE_CONTATO,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'41777788888','Lucia Maria','6166666666','2021-05-04'));
INSERT INTO TB_CONTATOS(NU_CONTATO,CO_CPF_CONTATO,NO_NOME_CONTATO,CO_TELEFONE_CONTATO,DT_ULTIMA_ATUALIZACAO_CONTATO) VALUES(SEQ_CONTATO.NEXTVAL,'31222225555','Assis Lima','6155555555','2021-05-20'));

--TB_OPERADORAS
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (14,'Oi','C');
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (15,'Vivo','C');
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (41,'Tim','C');
INSERT INTO TB_OPERADORAS(CO_OPERADORA,NM_OPERADORA,TP_OPERADORA) VALUES (28,'Embratel','F');


