CREATE USER SISCOMP IDENTIFIED BY 12345;
GRANT CONNECT TO SISCOMP;
GRANT CONNECT, RESOURCE to SISCOMP;
GRANT UNLIMITED TABLESPACE TO SISCOMP;
--GRANT SELECT,INSERT, UPDATE, DELETE ON SISCOMP TO SISCOMP;